# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
controller:
  ingressClassResource:
    default: true
  service:
    targetPorts:
      http: http
      https: http
    # Consider also these tweaks to allow getting real client IP in nginx
    # https://github.com/kubernetes/ingress-nginx/blob/d16e0dec4865cbd5b937dbffb957423c308331c5/hack/manifest-templates/provider/aws/nlb-with-tls-termination/values.yaml
    # https://github.com/kubernetes/ingress-nginx/blob/main/deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml#L334-L343
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:XX-XXXX-X:XXXXXXXXX:certificate/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
      # Classic LBs don't support websockets, use NLB
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # loadBalancerSourceRanges:
    #   # https://api.github.com/meta
    #   - 192.30.252.0/22
    #   - 185.199.108.0/22
    #   - 140.82.112.0/20
    #   - 143.55.64.0/20
    #   # https://codefresh.io/csdp-docs/docs/administration/platform-ip-addresses/
    #   - 107.21.238.215/32
    #   - 18.209.185.91/32
    #   - 18.215.207.215/32
    #   - 18.233.130.31/32
    #   - 18.210.174.176/32
    #   - 23.20.5.235/32
    #   - 3.232.154.67/32
    #   - 34.192.31.53/32
    #   - 34.193.111.98/32
    #   - 34.195.17.245/32
    #   - 34.196.33.69/32
    #   - 34.198.38.4/32
    #   - 34.200.163.76/32
    #   - 44.238.236.43/32
    #   - 44.234.209.117/32
    #   - 44.239.141.205/32
    #   - 44.228.66.171/32
    #   - 44.238.167.159/32
    #   - 44.237.63.217/32