---
apiVersion: v1
kind: Secret
metadata:
  name: quay-regcreds
data:
  .dockerconfigjson: <>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-creds
data:
  username: <>
  password: <>
  domain: <>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
data:
  token: <>
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: jira-creds
data:
  email: <>
  token: <>
type: Opaque
